### ISSUE TITLE
Не совместим с Drupal 9

### ISSUE THREAD

**Issue by superromeo** [yoomoney/cms-drupal8#12]
Говорит:
> Данная версия несовместима с Drupal 9.1.7-dev и должна быть заменена.

И действительно, в yookassa.info.yml видим:
> core: 8.x

 И как же быть?

**Comment by ostulov** [comment]
Добрый день!

На текущий момент наш модуль еще не поддерживает Drupal 9.x. Мы проверим работу модуля на новой версии Drupal  и подготовим отдельный модуль.

**Comment by ostulov** [comment]
С версии модуля v2.1.0 мы добавили совместимость с Drupal 9.x

**Comment by tonchik-tm** [comment]
https://www.drupal.org/docs/creating-custom-modules/let-drupal-know-about-your-module-with-an-infoyml-file

**Specifying the core_version_requirement when needed**

The new core_version_requirement key in *.info.yml files for modules, themes, and profiles now supports semantic versioning as implemented by the Composer project. This allows modules, themes, and profiles to also specify that they are compatible with multiple major versions of Drupal core.

For example a module that is compatible with Drupal 8 and Drupal 9 can have a info.yml file like this
```
name: My Module
type: module
core: 8.x
core_version_requirement: ^8 || ^9
```
**This specifies that the module is compatible with all versions of Drupal 8 and 9.** The core: is required here because Drupal Core versions before 8.7.7 do not recognize the core_version_requirement: key.

**Проверяли на версии Drupal 9.2.6**
![image](https://user-images.githubusercontent.com/2989751/136397677-f4d44bda-3689-43a0-91af-674cb64a862a.png)

Попробуйте поставить модуль через composer.json:

```
...
"yoomoney/yookassa-sdk-php": "^2.0",
"drupal/commerce_yookassa": "^2.1",
...
```

**Comment by superromeo** [comment]
А почему бы не добавить
`"yoomoney/yookassa-sdk-php": "^2.0", `
 в `require`?
